apiVersion: apps/v1
kind: Deployment
metadata:
   name: udacity-py-helloworld-deployment
   labels:
    app: udacity-py-helloworld
    name: udacity-py-helloworld
    
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-py-helloworld
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 1



  template:
    metadata:
      
      labels:
        app: udacity-py-helloworld
    spec:
      containers:
      - image: ahmedfathy/udacity-py-helloworld:v1.0.1
        name: udacity-py-helloworld
        resources: 
          limits:
            cpu: "500m"
            memory: "256Mi"
        ports:
          - containerPort: 5000

