name: Build Python helloworld app
on: [push]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout branch
        uses: actions/checkout@v4
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - 
        name: Docker build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: MyDockerfile.dockerfile
          push: true
          tags: ahmedfathy/udacity-py-helloworld:v1.2.0
          platforms: linux/amd64,linux/arm64
      
      - 
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
