name: Get Python Version
on:
  - push
jobs:
  Get-Python-Version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python --version

    