name: Get Python Version
on:
  - push
jobs:
  Get-Python-Version:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python --version

    